// Auto-generated by gen_all_partitions_tests.py
#include <algorithm>
#include <array>
#include <gtest/gtest.h>
#include <vector>

#include "dartfrog.hpp"
#include "datalog.hpp"

using df::datalog::Datalog;
using df::datalog::Predicate;
using df::datalog::Var;
using Edge = std::array<int32_t, 2>;

TEST(AllPartitions, n3_p0_0_1_2) {
    Datalog dl;
    Predicate<int32_t, 3> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(result(Var<0>{}, Var<1>{}, Var<2>{}) %=
                edge(Var<0>{}, Var<1>{}) && edge(Var<1>{}, Var<2>{}));
    edge.insert(df::Relation<Edge>::from_vec({{0, 1}, {1, 2}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 3>> expected = {{0, 1, 2}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n4_p0_0_1_2_3) {
    Datalog dl;
    Predicate<int32_t, 4> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}) %=
                edge(Var<0>{}, Var<1>{}) && edge(Var<1>{}, Var<2>{}) &&
                edge(Var<2>{}, Var<3>{}));
    edge.insert(df::Relation<Edge>::from_vec({{0, 1}, {1, 2}, {2, 3}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 4>> expected = {{0, 1, 2, 3}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n4_p1_0_1_2_3) {
    Datalog dl;
    Predicate<int32_t, 4> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}) %=
                edge(Var<0>{}, Var<1>{}) && edge(Var<2>{}, Var<3>{}));
    edge.insert(df::Relation<Edge>::from_vec({{0, 1}, {1002, 1003}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 4>> expected = {{0, 1, 0, 1},
                                                    {0, 1, 1002, 1003},
                                                    {1002, 1003, 0, 1},
                                                    {1002, 1003, 1002, 1003}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n4_p2_1_2_0_3) {
    Datalog dl;
    Predicate<int32_t, 4> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}) %=
                edge(Var<1>{}, Var<2>{}) && edge(Var<0>{}, Var<3>{}));
    edge.insert(df::Relation<Edge>::from_vec({{1, 2}, {1000, 1003}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 4>> expected = {{1, 1, 2, 2},
                                                    {1, 1000, 1003, 2},
                                                    {1000, 1, 2, 1003},
                                                    {1000, 1000, 1003, 1003}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n4_p3_0_2_1_3) {
    Datalog dl;
    Predicate<int32_t, 4> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}) %=
                edge(Var<0>{}, Var<2>{}) && edge(Var<1>{}, Var<3>{}));
    edge.insert(df::Relation<Edge>::from_vec({{0, 2}, {1001, 1003}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 4>> expected = {{0, 0, 2, 2},
                                                    {0, 1001, 2, 1003},
                                                    {1001, 0, 1003, 2},
                                                    {1001, 1001, 1003, 1003}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n5_p0_0_1_2_3_4) {
    Datalog dl;
    Predicate<int32_t, 5> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{}) %=
                edge(Var<0>{}, Var<1>{}) && edge(Var<1>{}, Var<2>{}) &&
                edge(Var<2>{}, Var<3>{}) && edge(Var<3>{}, Var<4>{}));
    edge.insert(df::Relation<Edge>::from_vec({{0, 1}, {1, 2}, {2, 3}, {3, 4}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 5>> expected = {{0, 1, 2, 3, 4}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n5_p1_0_1_2_3_4) {
    Datalog dl;
    Predicate<int32_t, 5> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{}) %=
                edge(Var<0>{}, Var<1>{}) && edge(Var<2>{}, Var<3>{}) &&
                edge(Var<3>{}, Var<4>{}));
    edge.insert(
        df::Relation<Edge>::from_vec({{0, 1}, {1002, 1003}, {1003, 1004}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 5>> expected = {
        {0, 1, 1002, 1003, 1004},
        {1002, 1003, 1002, 1003, 1004},
        {1003, 1004, 1002, 1003, 1004}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n5_p2_0_1_2_3_4) {
    Datalog dl;
    Predicate<int32_t, 5> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{}) %=
                edge(Var<0>{}, Var<1>{}) && edge(Var<1>{}, Var<2>{}) &&
                edge(Var<3>{}, Var<4>{}));
    edge.insert(df::Relation<Edge>::from_vec({{0, 1}, {1, 2}, {1003, 1004}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 5>> expected = {
        {0, 1, 2, 0, 1}, {0, 1, 2, 1, 2}, {0, 1, 2, 1003, 1004}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n5_p3_1_2_0_3_4) {
    Datalog dl;
    Predicate<int32_t, 5> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{}) %=
                edge(Var<1>{}, Var<2>{}) && edge(Var<0>{}, Var<3>{}) &&
                edge(Var<3>{}, Var<4>{}));
    edge.insert(
        df::Relation<Edge>::from_vec({{1, 2}, {1000, 1003}, {1003, 1004}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 5>> expected = {
        {1000, 1, 2, 1003, 1004},
        {1000, 1000, 1003, 1003, 1004},
        {1000, 1003, 1004, 1003, 1004}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n5_p4_0_2_1_3_4) {
    Datalog dl;
    Predicate<int32_t, 5> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{}) %=
                edge(Var<0>{}, Var<2>{}) && edge(Var<1>{}, Var<3>{}) &&
                edge(Var<3>{}, Var<4>{}));
    edge.insert(
        df::Relation<Edge>::from_vec({{0, 2}, {1001, 1003}, {1003, 1004}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 5>> expected = {
        {0, 1001, 2, 1003, 1004},
        {1001, 1001, 1003, 1003, 1004},
        {1003, 1001, 1004, 1003, 1004}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n5_p5_1_2_3_0_4) {
    Datalog dl;
    Predicate<int32_t, 5> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{}) %=
                edge(Var<1>{}, Var<2>{}) && edge(Var<2>{}, Var<3>{}) &&
                edge(Var<0>{}, Var<4>{}));
    edge.insert(df::Relation<Edge>::from_vec({{1, 2}, {2, 3}, {1000, 1004}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 5>> expected = {
        {1, 1, 2, 3, 2}, {2, 1, 2, 3, 3}, {1000, 1, 2, 3, 1004}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n5_p6_0_2_3_1_4) {
    Datalog dl;
    Predicate<int32_t, 5> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{}) %=
                edge(Var<0>{}, Var<2>{}) && edge(Var<2>{}, Var<3>{}) &&
                edge(Var<1>{}, Var<4>{}));
    edge.insert(df::Relation<Edge>::from_vec({{0, 2}, {2, 3}, {1001, 1004}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 5>> expected = {
        {0, 0, 2, 3, 2}, {0, 2, 2, 3, 3}, {0, 1001, 2, 3, 1004}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n5_p7_2_3_0_1_4) {
    Datalog dl;
    Predicate<int32_t, 5> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{}) %=
                edge(Var<2>{}, Var<3>{}) && edge(Var<0>{}, Var<1>{}) &&
                edge(Var<1>{}, Var<4>{}));
    edge.insert(
        df::Relation<Edge>::from_vec({{2, 3}, {1000, 1001}, {1001, 1004}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 5>> expected = {
        {1000, 1001, 2, 3, 1004},
        {1000, 1001, 1000, 1001, 1004},
        {1000, 1001, 1001, 1004, 1004}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n5_p8_0_1_3_2_4) {
    Datalog dl;
    Predicate<int32_t, 5> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{}) %=
                edge(Var<0>{}, Var<1>{}) && edge(Var<1>{}, Var<3>{}) &&
                edge(Var<2>{}, Var<4>{}));
    edge.insert(df::Relation<Edge>::from_vec({{0, 1}, {1, 3}, {1002, 1004}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 5>> expected = {
        {0, 1, 0, 3, 1}, {0, 1, 1, 3, 3}, {0, 1, 1002, 3, 1004}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n5_p9_1_3_0_2_4) {
    Datalog dl;
    Predicate<int32_t, 5> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{}) %=
                edge(Var<1>{}, Var<3>{}) && edge(Var<0>{}, Var<2>{}) &&
                edge(Var<2>{}, Var<4>{}));
    edge.insert(
        df::Relation<Edge>::from_vec({{1, 3}, {1000, 1002}, {1002, 1004}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 5>> expected = {
        {1000, 1, 1002, 3, 1004},
        {1000, 1000, 1002, 1002, 1004},
        {1000, 1002, 1002, 1004, 1004}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n5_p10_0_3_1_2_4) {
    Datalog dl;
    Predicate<int32_t, 5> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{}) %=
                edge(Var<0>{}, Var<3>{}) && edge(Var<1>{}, Var<2>{}) &&
                edge(Var<2>{}, Var<4>{}));
    edge.insert(
        df::Relation<Edge>::from_vec({{0, 3}, {1001, 1002}, {1002, 1004}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 5>> expected = {
        {0, 1001, 1002, 3, 1004},
        {1001, 1001, 1002, 1002, 1004},
        {1002, 1001, 1002, 1004, 1004}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p0_0_1_2_3_4_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(
        result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{}, Var<5>{}) %=
        edge(Var<0>{}, Var<1>{}) && edge(Var<1>{}, Var<2>{}) &&
        edge(Var<2>{}, Var<3>{}) && edge(Var<3>{}, Var<4>{}) &&
        edge(Var<4>{}, Var<5>{}));
    edge.insert(
        df::Relation<Edge>::from_vec({{0, 1}, {1, 2}, {2, 3}, {3, 4}, {4, 5}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {{0, 1, 2, 3, 4, 5}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p1_0_1_2_3_4_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(
        result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{}, Var<5>{}) %=
        edge(Var<0>{}, Var<1>{}) && edge(Var<2>{}, Var<3>{}) &&
        edge(Var<3>{}, Var<4>{}) && edge(Var<4>{}, Var<5>{}));
    edge.insert(df::Relation<Edge>::from_vec(
        {{0, 1}, {1002, 1003}, {1003, 1004}, {1004, 1005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {
        {0, 1, 1002, 1003, 1004, 1005},
        {1002, 1003, 1002, 1003, 1004, 1005},
        {1003, 1004, 1002, 1003, 1004, 1005},
        {1004, 1005, 1002, 1003, 1004, 1005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p2_0_1_2_3_4_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(
        result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{}, Var<5>{}) %=
        edge(Var<0>{}, Var<1>{}) && edge(Var<1>{}, Var<2>{}) &&
        edge(Var<3>{}, Var<4>{}) && edge(Var<4>{}, Var<5>{}));
    edge.insert(df::Relation<Edge>::from_vec(
        {{0, 1}, {1, 2}, {1003, 1004}, {1004, 1005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {
        {0, 1, 2, 0, 1, 2},
        {0, 1, 2, 1003, 1004, 1005},
        {1003, 1004, 1005, 0, 1, 2},
        {1003, 1004, 1005, 1003, 1004, 1005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p3_1_2_0_3_4_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(
        result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{}, Var<5>{}) %=
        edge(Var<1>{}, Var<2>{}) && edge(Var<0>{}, Var<3>{}) &&
        edge(Var<3>{}, Var<4>{}) && edge(Var<4>{}, Var<5>{}));
    edge.insert(df::Relation<Edge>::from_vec(
        {{1, 2}, {1000, 1003}, {1003, 1004}, {1004, 1005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {
        {1000, 1, 2, 1003, 1004, 1005},
        {1000, 1000, 1003, 1003, 1004, 1005},
        {1000, 1003, 1004, 1003, 1004, 1005},
        {1000, 1004, 1005, 1003, 1004, 1005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p4_0_2_1_3_4_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(
        result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{}, Var<5>{}) %=
        edge(Var<0>{}, Var<2>{}) && edge(Var<1>{}, Var<3>{}) &&
        edge(Var<3>{}, Var<4>{}) && edge(Var<4>{}, Var<5>{}));
    edge.insert(df::Relation<Edge>::from_vec(
        {{0, 2}, {1001, 1003}, {1003, 1004}, {1004, 1005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {
        {0, 1001, 2, 1003, 1004, 1005},
        {1001, 1001, 1003, 1003, 1004, 1005},
        {1003, 1001, 1004, 1003, 1004, 1005},
        {1004, 1001, 1005, 1003, 1004, 1005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p5_0_1_2_3_4_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(
        result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{}, Var<5>{}) %=
        edge(Var<0>{}, Var<1>{}) && edge(Var<1>{}, Var<2>{}) &&
        edge(Var<2>{}, Var<3>{}) && edge(Var<4>{}, Var<5>{}));
    edge.insert(
        df::Relation<Edge>::from_vec({{0, 1}, {1, 2}, {2, 3}, {1004, 1005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {{0, 1, 2, 3, 0, 1},
                                                    {0, 1, 2, 3, 1, 2},
                                                    {0, 1, 2, 3, 2, 3},
                                                    {0, 1, 2, 3, 1004, 1005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p6_1_2_3_0_4_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(
        result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{}, Var<5>{}) %=
        edge(Var<1>{}, Var<2>{}) && edge(Var<2>{}, Var<3>{}) &&
        edge(Var<0>{}, Var<4>{}) && edge(Var<4>{}, Var<5>{}));
    edge.insert(df::Relation<Edge>::from_vec(
        {{1, 2}, {2, 3}, {1000, 1004}, {1004, 1005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {
        {1, 1, 2, 3, 2, 3},
        {1, 1000, 1004, 1005, 2, 3},
        {1000, 1, 2, 3, 1004, 1005},
        {1000, 1000, 1004, 1005, 1004, 1005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p7_0_2_3_1_4_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(
        result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{}, Var<5>{}) %=
        edge(Var<0>{}, Var<2>{}) && edge(Var<2>{}, Var<3>{}) &&
        edge(Var<1>{}, Var<4>{}) && edge(Var<4>{}, Var<5>{}));
    edge.insert(df::Relation<Edge>::from_vec(
        {{0, 2}, {2, 3}, {1001, 1004}, {1004, 1005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {
        {0, 0, 2, 3, 2, 3},
        {0, 1001, 2, 3, 1004, 1005},
        {1001, 0, 1004, 1005, 2, 3},
        {1001, 1001, 1004, 1005, 1004, 1005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p8_2_3_0_1_4_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(
        result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{}, Var<5>{}) %=
        edge(Var<2>{}, Var<3>{}) && edge(Var<0>{}, Var<1>{}) &&
        edge(Var<1>{}, Var<4>{}) && edge(Var<4>{}, Var<5>{}));
    edge.insert(df::Relation<Edge>::from_vec(
        {{2, 3}, {1000, 1001}, {1001, 1004}, {1004, 1005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {
        {1000, 1001, 2, 3, 1004, 1005},
        {1000, 1001, 1000, 1001, 1004, 1005},
        {1000, 1001, 1001, 1004, 1004, 1005},
        {1000, 1001, 1004, 1005, 1004, 1005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p9_0_1_2_3_4_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{},
                       Var<5>{}) %= edge(Var<0>{}, Var<1>{}) &&
                                    edge(Var<2>{}, Var<3>{}) &&
                                    edge(Var<4>{}, Var<5>{}));
    edge.insert(
        df::Relation<Edge>::from_vec({{0, 1}, {1002, 1003}, {2004, 2005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {
        {0, 1, 0, 1, 0, 1},
        {0, 1, 0, 1, 1002, 1003},
        {0, 1, 0, 1, 2004, 2005},
        {0, 1, 1002, 1003, 0, 1},
        {0, 1, 1002, 1003, 1002, 1003},
        {0, 1, 1002, 1003, 2004, 2005},
        {0, 1, 2004, 2005, 0, 1},
        {0, 1, 2004, 2005, 1002, 1003},
        {0, 1, 2004, 2005, 2004, 2005},
        {1002, 1003, 0, 1, 0, 1},
        {1002, 1003, 0, 1, 1002, 1003},
        {1002, 1003, 0, 1, 2004, 2005},
        {1002, 1003, 1002, 1003, 0, 1},
        {1002, 1003, 1002, 1003, 1002, 1003},
        {1002, 1003, 1002, 1003, 2004, 2005},
        {1002, 1003, 2004, 2005, 0, 1},
        {1002, 1003, 2004, 2005, 1002, 1003},
        {1002, 1003, 2004, 2005, 2004, 2005},
        {2004, 2005, 0, 1, 0, 1},
        {2004, 2005, 0, 1, 1002, 1003},
        {2004, 2005, 0, 1, 2004, 2005},
        {2004, 2005, 1002, 1003, 0, 1},
        {2004, 2005, 1002, 1003, 1002, 1003},
        {2004, 2005, 1002, 1003, 2004, 2005},
        {2004, 2005, 2004, 2005, 0, 1},
        {2004, 2005, 2004, 2005, 1002, 1003},
        {2004, 2005, 2004, 2005, 2004, 2005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p10_0_1_3_2_4_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(
        result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{}, Var<5>{}) %=
        edge(Var<0>{}, Var<1>{}) && edge(Var<1>{}, Var<3>{}) &&
        edge(Var<2>{}, Var<4>{}) && edge(Var<4>{}, Var<5>{}));
    edge.insert(df::Relation<Edge>::from_vec(
        {{0, 1}, {1, 3}, {1002, 1004}, {1004, 1005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {
        {0, 1, 0, 3, 1, 3},
        {0, 1, 1002, 3, 1004, 1005},
        {1002, 1004, 0, 1005, 1, 3},
        {1002, 1004, 1002, 1005, 1004, 1005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p11_1_3_0_2_4_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(
        result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{}, Var<5>{}) %=
        edge(Var<1>{}, Var<3>{}) && edge(Var<0>{}, Var<2>{}) &&
        edge(Var<2>{}, Var<4>{}) && edge(Var<4>{}, Var<5>{}));
    edge.insert(df::Relation<Edge>::from_vec(
        {{1, 3}, {1000, 1002}, {1002, 1004}, {1004, 1005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {
        {1000, 1, 1002, 3, 1004, 1005},
        {1000, 1000, 1002, 1002, 1004, 1005},
        {1000, 1002, 1002, 1004, 1004, 1005},
        {1000, 1004, 1002, 1005, 1004, 1005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p12_0_3_1_2_4_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(
        result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{}, Var<5>{}) %=
        edge(Var<0>{}, Var<3>{}) && edge(Var<1>{}, Var<2>{}) &&
        edge(Var<2>{}, Var<4>{}) && edge(Var<4>{}, Var<5>{}));
    edge.insert(df::Relation<Edge>::from_vec(
        {{0, 3}, {1001, 1002}, {1002, 1004}, {1004, 1005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {
        {0, 1001, 1002, 3, 1004, 1005},
        {1001, 1001, 1002, 1002, 1004, 1005},
        {1002, 1001, 1002, 1004, 1004, 1005},
        {1004, 1001, 1002, 1005, 1004, 1005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p13_1_2_0_3_4_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{},
                       Var<5>{}) %= edge(Var<1>{}, Var<2>{}) &&
                                    edge(Var<0>{}, Var<3>{}) &&
                                    edge(Var<4>{}, Var<5>{}));
    edge.insert(
        df::Relation<Edge>::from_vec({{1, 2}, {1000, 1003}, {2004, 2005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {
        {1, 1, 2, 2, 1, 2},
        {1, 1, 2, 2, 1000, 1003},
        {1, 1, 2, 2, 2004, 2005},
        {1, 1000, 1003, 2, 1, 2},
        {1, 1000, 1003, 2, 1000, 1003},
        {1, 1000, 1003, 2, 2004, 2005},
        {1, 2004, 2005, 2, 1, 2},
        {1, 2004, 2005, 2, 1000, 1003},
        {1, 2004, 2005, 2, 2004, 2005},
        {1000, 1, 2, 1003, 1, 2},
        {1000, 1, 2, 1003, 1000, 1003},
        {1000, 1, 2, 1003, 2004, 2005},
        {1000, 1000, 1003, 1003, 1, 2},
        {1000, 1000, 1003, 1003, 1000, 1003},
        {1000, 1000, 1003, 1003, 2004, 2005},
        {1000, 2004, 2005, 1003, 1, 2},
        {1000, 2004, 2005, 1003, 1000, 1003},
        {1000, 2004, 2005, 1003, 2004, 2005},
        {2004, 1, 2, 2005, 1, 2},
        {2004, 1, 2, 2005, 1000, 1003},
        {2004, 1, 2, 2005, 2004, 2005},
        {2004, 1000, 1003, 2005, 1, 2},
        {2004, 1000, 1003, 2005, 1000, 1003},
        {2004, 1000, 1003, 2005, 2004, 2005},
        {2004, 2004, 2005, 2005, 1, 2},
        {2004, 2004, 2005, 2005, 1000, 1003},
        {2004, 2004, 2005, 2005, 2004, 2005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p14_0_2_1_3_4_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{},
                       Var<5>{}) %= edge(Var<0>{}, Var<2>{}) &&
                                    edge(Var<1>{}, Var<3>{}) &&
                                    edge(Var<4>{}, Var<5>{}));
    edge.insert(
        df::Relation<Edge>::from_vec({{0, 2}, {1001, 1003}, {2004, 2005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {
        {0, 0, 2, 2, 0, 2},
        {0, 0, 2, 2, 1001, 1003},
        {0, 0, 2, 2, 2004, 2005},
        {0, 1001, 2, 1003, 0, 2},
        {0, 1001, 2, 1003, 1001, 1003},
        {0, 1001, 2, 1003, 2004, 2005},
        {0, 2004, 2, 2005, 0, 2},
        {0, 2004, 2, 2005, 1001, 1003},
        {0, 2004, 2, 2005, 2004, 2005},
        {1001, 0, 1003, 2, 0, 2},
        {1001, 0, 1003, 2, 1001, 1003},
        {1001, 0, 1003, 2, 2004, 2005},
        {1001, 1001, 1003, 1003, 0, 2},
        {1001, 1001, 1003, 1003, 1001, 1003},
        {1001, 1001, 1003, 1003, 2004, 2005},
        {1001, 2004, 1003, 2005, 0, 2},
        {1001, 2004, 1003, 2005, 1001, 1003},
        {1001, 2004, 1003, 2005, 2004, 2005},
        {2004, 0, 2005, 2, 0, 2},
        {2004, 0, 2005, 2, 1001, 1003},
        {2004, 0, 2005, 2, 2004, 2005},
        {2004, 1001, 2005, 1003, 0, 2},
        {2004, 1001, 2005, 1003, 1001, 1003},
        {2004, 1001, 2005, 1003, 2004, 2005},
        {2004, 2004, 2005, 2005, 0, 2},
        {2004, 2004, 2005, 2005, 1001, 1003},
        {2004, 2004, 2005, 2005, 2004, 2005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p15_1_2_3_4_0_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(
        result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{}, Var<5>{}) %=
        edge(Var<1>{}, Var<2>{}) && edge(Var<2>{}, Var<3>{}) &&
        edge(Var<3>{}, Var<4>{}) && edge(Var<0>{}, Var<5>{}));
    edge.insert(
        df::Relation<Edge>::from_vec({{1, 2}, {2, 3}, {3, 4}, {1000, 1005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {{1, 1, 2, 3, 4, 2},
                                                    {2, 1, 2, 3, 4, 3},
                                                    {3, 1, 2, 3, 4, 4},
                                                    {1000, 1, 2, 3, 4, 1005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p16_0_2_3_4_1_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(
        result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{}, Var<5>{}) %=
        edge(Var<0>{}, Var<2>{}) && edge(Var<2>{}, Var<3>{}) &&
        edge(Var<3>{}, Var<4>{}) && edge(Var<1>{}, Var<5>{}));
    edge.insert(
        df::Relation<Edge>::from_vec({{0, 2}, {2, 3}, {3, 4}, {1001, 1005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {{0, 0, 2, 3, 4, 2},
                                                    {0, 2, 2, 3, 4, 3},
                                                    {0, 3, 2, 3, 4, 4},
                                                    {0, 1001, 2, 3, 4, 1005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p17_2_3_4_0_1_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(
        result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{}, Var<5>{}) %=
        edge(Var<2>{}, Var<3>{}) && edge(Var<3>{}, Var<4>{}) &&
        edge(Var<0>{}, Var<1>{}) && edge(Var<1>{}, Var<5>{}));
    edge.insert(df::Relation<Edge>::from_vec(
        {{2, 3}, {3, 4}, {1000, 1001}, {1001, 1005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {
        {2, 3, 2, 3, 4, 4},
        {2, 3, 1000, 1001, 1005, 4},
        {1000, 1001, 2, 3, 4, 1005},
        {1000, 1001, 1000, 1001, 1005, 1005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p18_0_1_3_4_2_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(
        result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{}, Var<5>{}) %=
        edge(Var<0>{}, Var<1>{}) && edge(Var<1>{}, Var<3>{}) &&
        edge(Var<3>{}, Var<4>{}) && edge(Var<2>{}, Var<5>{}));
    edge.insert(
        df::Relation<Edge>::from_vec({{0, 1}, {1, 3}, {3, 4}, {1002, 1005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {{0, 1, 0, 3, 4, 1},
                                                    {0, 1, 1, 3, 4, 3},
                                                    {0, 1, 3, 3, 4, 4},
                                                    {0, 1, 1002, 3, 4, 1005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p19_1_3_4_0_2_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(
        result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{}, Var<5>{}) %=
        edge(Var<1>{}, Var<3>{}) && edge(Var<3>{}, Var<4>{}) &&
        edge(Var<0>{}, Var<2>{}) && edge(Var<2>{}, Var<5>{}));
    edge.insert(df::Relation<Edge>::from_vec(
        {{1, 3}, {3, 4}, {1000, 1002}, {1002, 1005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {
        {1, 1, 3, 3, 4, 4},
        {1, 1000, 3, 1002, 1005, 4},
        {1000, 1, 1002, 3, 4, 1005},
        {1000, 1000, 1002, 1002, 1005, 1005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p20_0_3_4_1_2_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(
        result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{}, Var<5>{}) %=
        edge(Var<0>{}, Var<3>{}) && edge(Var<3>{}, Var<4>{}) &&
        edge(Var<1>{}, Var<2>{}) && edge(Var<2>{}, Var<5>{}));
    edge.insert(df::Relation<Edge>::from_vec(
        {{0, 3}, {3, 4}, {1001, 1002}, {1002, 1005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {
        {0, 0, 3, 3, 4, 4},
        {0, 1001, 1002, 3, 4, 1005},
        {1001, 0, 3, 1002, 1005, 4},
        {1001, 1001, 1002, 1002, 1005, 1005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p21_3_4_0_1_2_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(
        result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{}, Var<5>{}) %=
        edge(Var<3>{}, Var<4>{}) && edge(Var<0>{}, Var<1>{}) &&
        edge(Var<1>{}, Var<2>{}) && edge(Var<2>{}, Var<5>{}));
    edge.insert(df::Relation<Edge>::from_vec(
        {{3, 4}, {1000, 1001}, {1001, 1002}, {1002, 1005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {
        {1000, 1001, 1002, 3, 4, 1005},
        {1000, 1001, 1002, 1000, 1001, 1005},
        {1000, 1001, 1002, 1001, 1002, 1005},
        {1000, 1001, 1002, 1002, 1005, 1005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p22_0_1_3_4_2_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{},
                       Var<5>{}) %= edge(Var<0>{}, Var<1>{}) &&
                                    edge(Var<3>{}, Var<4>{}) &&
                                    edge(Var<2>{}, Var<5>{}));
    edge.insert(
        df::Relation<Edge>::from_vec({{0, 1}, {1003, 1004}, {2002, 2005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {
        {0, 1, 0, 0, 1, 1},
        {0, 1, 0, 1003, 1004, 1},
        {0, 1, 0, 2002, 2005, 1},
        {0, 1, 1003, 0, 1, 1004},
        {0, 1, 1003, 1003, 1004, 1004},
        {0, 1, 1003, 2002, 2005, 1004},
        {0, 1, 2002, 0, 1, 2005},
        {0, 1, 2002, 1003, 1004, 2005},
        {0, 1, 2002, 2002, 2005, 2005},
        {1003, 1004, 0, 0, 1, 1},
        {1003, 1004, 0, 1003, 1004, 1},
        {1003, 1004, 0, 2002, 2005, 1},
        {1003, 1004, 1003, 0, 1, 1004},
        {1003, 1004, 1003, 1003, 1004, 1004},
        {1003, 1004, 1003, 2002, 2005, 1004},
        {1003, 1004, 2002, 0, 1, 2005},
        {1003, 1004, 2002, 1003, 1004, 2005},
        {1003, 1004, 2002, 2002, 2005, 2005},
        {2002, 2005, 0, 0, 1, 1},
        {2002, 2005, 0, 1003, 1004, 1},
        {2002, 2005, 0, 2002, 2005, 1},
        {2002, 2005, 1003, 0, 1, 1004},
        {2002, 2005, 1003, 1003, 1004, 1004},
        {2002, 2005, 1003, 2002, 2005, 1004},
        {2002, 2005, 2002, 0, 1, 2005},
        {2002, 2005, 2002, 1003, 1004, 2005},
        {2002, 2005, 2002, 2002, 2005, 2005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p23_1_2_3_4_0_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{},
                       Var<5>{}) %= edge(Var<1>{}, Var<2>{}) &&
                                    edge(Var<3>{}, Var<4>{}) &&
                                    edge(Var<0>{}, Var<5>{}));
    edge.insert(
        df::Relation<Edge>::from_vec({{1, 2}, {1003, 1004}, {2000, 2005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {
        {1, 1, 2, 1, 2, 2},
        {1, 1, 2, 1003, 1004, 2},
        {1, 1, 2, 2000, 2005, 2},
        {1, 1003, 1004, 1, 2, 2},
        {1, 1003, 1004, 1003, 1004, 2},
        {1, 1003, 1004, 2000, 2005, 2},
        {1, 2000, 2005, 1, 2, 2},
        {1, 2000, 2005, 1003, 1004, 2},
        {1, 2000, 2005, 2000, 2005, 2},
        {1003, 1, 2, 1, 2, 1004},
        {1003, 1, 2, 1003, 1004, 1004},
        {1003, 1, 2, 2000, 2005, 1004},
        {1003, 1003, 1004, 1, 2, 1004},
        {1003, 1003, 1004, 1003, 1004, 1004},
        {1003, 1003, 1004, 2000, 2005, 1004},
        {1003, 2000, 2005, 1, 2, 1004},
        {1003, 2000, 2005, 1003, 1004, 1004},
        {1003, 2000, 2005, 2000, 2005, 1004},
        {2000, 1, 2, 1, 2, 2005},
        {2000, 1, 2, 1003, 1004, 2005},
        {2000, 1, 2, 2000, 2005, 2005},
        {2000, 1003, 1004, 1, 2, 2005},
        {2000, 1003, 1004, 1003, 1004, 2005},
        {2000, 1003, 1004, 2000, 2005, 2005},
        {2000, 2000, 2005, 1, 2, 2005},
        {2000, 2000, 2005, 1003, 1004, 2005},
        {2000, 2000, 2005, 2000, 2005, 2005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p24_0_2_3_4_1_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{},
                       Var<5>{}) %= edge(Var<0>{}, Var<2>{}) &&
                                    edge(Var<3>{}, Var<4>{}) &&
                                    edge(Var<1>{}, Var<5>{}));
    edge.insert(
        df::Relation<Edge>::from_vec({{0, 2}, {1003, 1004}, {2001, 2005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {
        {0, 0, 2, 0, 2, 2},
        {0, 0, 2, 1003, 1004, 2},
        {0, 0, 2, 2001, 2005, 2},
        {0, 1003, 2, 0, 2, 1004},
        {0, 1003, 2, 1003, 1004, 1004},
        {0, 1003, 2, 2001, 2005, 1004},
        {0, 2001, 2, 0, 2, 2005},
        {0, 2001, 2, 1003, 1004, 2005},
        {0, 2001, 2, 2001, 2005, 2005},
        {1003, 0, 1004, 0, 2, 2},
        {1003, 0, 1004, 1003, 1004, 2},
        {1003, 0, 1004, 2001, 2005, 2},
        {1003, 1003, 1004, 0, 2, 1004},
        {1003, 1003, 1004, 1003, 1004, 1004},
        {1003, 1003, 1004, 2001, 2005, 1004},
        {1003, 2001, 1004, 0, 2, 2005},
        {1003, 2001, 1004, 1003, 1004, 2005},
        {1003, 2001, 1004, 2001, 2005, 2005},
        {2001, 0, 2005, 0, 2, 2},
        {2001, 0, 2005, 1003, 1004, 2},
        {2001, 0, 2005, 2001, 2005, 2},
        {2001, 1003, 2005, 0, 2, 1004},
        {2001, 1003, 2005, 1003, 1004, 1004},
        {2001, 1003, 2005, 2001, 2005, 1004},
        {2001, 2001, 2005, 0, 2, 2005},
        {2001, 2001, 2005, 1003, 1004, 2005},
        {2001, 2001, 2005, 2001, 2005, 2005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p25_0_1_2_4_3_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(
        result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{}, Var<5>{}) %=
        edge(Var<0>{}, Var<1>{}) && edge(Var<1>{}, Var<2>{}) &&
        edge(Var<2>{}, Var<4>{}) && edge(Var<3>{}, Var<5>{}));
    edge.insert(
        df::Relation<Edge>::from_vec({{0, 1}, {1, 2}, {2, 4}, {1003, 1005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {{0, 1, 2, 0, 4, 1},
                                                    {0, 1, 2, 1, 4, 2},
                                                    {0, 1, 2, 2, 4, 4},
                                                    {0, 1, 2, 1003, 4, 1005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p26_1_2_4_0_3_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(
        result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{}, Var<5>{}) %=
        edge(Var<1>{}, Var<2>{}) && edge(Var<2>{}, Var<4>{}) &&
        edge(Var<0>{}, Var<3>{}) && edge(Var<3>{}, Var<5>{}));
    edge.insert(df::Relation<Edge>::from_vec(
        {{1, 2}, {2, 4}, {1000, 1003}, {1003, 1005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {
        {1, 1, 2, 2, 4, 4},
        {1, 1000, 1003, 2, 1005, 4},
        {1000, 1, 2, 1003, 4, 1005},
        {1000, 1000, 1003, 1003, 1005, 1005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p27_0_2_4_1_3_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(
        result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{}, Var<5>{}) %=
        edge(Var<0>{}, Var<2>{}) && edge(Var<2>{}, Var<4>{}) &&
        edge(Var<1>{}, Var<3>{}) && edge(Var<3>{}, Var<5>{}));
    edge.insert(df::Relation<Edge>::from_vec(
        {{0, 2}, {2, 4}, {1001, 1003}, {1003, 1005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {
        {0, 0, 2, 2, 4, 4},
        {0, 1001, 2, 1003, 4, 1005},
        {1001, 0, 1003, 2, 1005, 4},
        {1001, 1001, 1003, 1003, 1005, 1005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p28_2_4_0_1_3_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(
        result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{}, Var<5>{}) %=
        edge(Var<2>{}, Var<4>{}) && edge(Var<0>{}, Var<1>{}) &&
        edge(Var<1>{}, Var<3>{}) && edge(Var<3>{}, Var<5>{}));
    edge.insert(df::Relation<Edge>::from_vec(
        {{2, 4}, {1000, 1001}, {1001, 1003}, {1003, 1005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {
        {1000, 1001, 2, 1003, 4, 1005},
        {1000, 1001, 1000, 1003, 1001, 1005},
        {1000, 1001, 1001, 1003, 1003, 1005},
        {1000, 1001, 1003, 1003, 1005, 1005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p29_0_1_2_4_3_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{},
                       Var<5>{}) %= edge(Var<0>{}, Var<1>{}) &&
                                    edge(Var<2>{}, Var<4>{}) &&
                                    edge(Var<3>{}, Var<5>{}));
    edge.insert(
        df::Relation<Edge>::from_vec({{0, 1}, {1002, 1004}, {2003, 2005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {
        {0, 1, 0, 0, 1, 1},
        {0, 1, 0, 1002, 1, 1004},
        {0, 1, 0, 2003, 1, 2005},
        {0, 1, 1002, 0, 1004, 1},
        {0, 1, 1002, 1002, 1004, 1004},
        {0, 1, 1002, 2003, 1004, 2005},
        {0, 1, 2003, 0, 2005, 1},
        {0, 1, 2003, 1002, 2005, 1004},
        {0, 1, 2003, 2003, 2005, 2005},
        {1002, 1004, 0, 0, 1, 1},
        {1002, 1004, 0, 1002, 1, 1004},
        {1002, 1004, 0, 2003, 1, 2005},
        {1002, 1004, 1002, 0, 1004, 1},
        {1002, 1004, 1002, 1002, 1004, 1004},
        {1002, 1004, 1002, 2003, 1004, 2005},
        {1002, 1004, 2003, 0, 2005, 1},
        {1002, 1004, 2003, 1002, 2005, 1004},
        {1002, 1004, 2003, 2003, 2005, 2005},
        {2003, 2005, 0, 0, 1, 1},
        {2003, 2005, 0, 1002, 1, 1004},
        {2003, 2005, 0, 2003, 1, 2005},
        {2003, 2005, 1002, 0, 1004, 1},
        {2003, 2005, 1002, 1002, 1004, 1004},
        {2003, 2005, 1002, 2003, 1004, 2005},
        {2003, 2005, 2003, 0, 2005, 1},
        {2003, 2005, 2003, 1002, 2005, 1004},
        {2003, 2005, 2003, 2003, 2005, 2005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p30_0_1_4_2_3_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(
        result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{}, Var<5>{}) %=
        edge(Var<0>{}, Var<1>{}) && edge(Var<1>{}, Var<4>{}) &&
        edge(Var<2>{}, Var<3>{}) && edge(Var<3>{}, Var<5>{}));
    edge.insert(df::Relation<Edge>::from_vec(
        {{0, 1}, {1, 4}, {1002, 1003}, {1003, 1005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {
        {0, 1, 0, 1, 4, 4},
        {0, 1, 1002, 1003, 4, 1005},
        {1002, 1003, 0, 1, 1005, 4},
        {1002, 1003, 1002, 1003, 1005, 1005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p31_1_4_0_2_3_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(
        result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{}, Var<5>{}) %=
        edge(Var<1>{}, Var<4>{}) && edge(Var<0>{}, Var<2>{}) &&
        edge(Var<2>{}, Var<3>{}) && edge(Var<3>{}, Var<5>{}));
    edge.insert(df::Relation<Edge>::from_vec(
        {{1, 4}, {1000, 1002}, {1002, 1003}, {1003, 1005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {
        {1000, 1, 1002, 1003, 4, 1005},
        {1000, 1000, 1002, 1003, 1002, 1005},
        {1000, 1002, 1002, 1003, 1003, 1005},
        {1000, 1003, 1002, 1003, 1005, 1005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p32_0_4_1_2_3_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(
        result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{}, Var<5>{}) %=
        edge(Var<0>{}, Var<4>{}) && edge(Var<1>{}, Var<2>{}) &&
        edge(Var<2>{}, Var<3>{}) && edge(Var<3>{}, Var<5>{}));
    edge.insert(df::Relation<Edge>::from_vec(
        {{0, 4}, {1001, 1002}, {1002, 1003}, {1003, 1005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {
        {0, 1001, 1002, 1003, 4, 1005},
        {1001, 1001, 1002, 1003, 1002, 1005},
        {1002, 1001, 1002, 1003, 1003, 1005},
        {1003, 1001, 1002, 1003, 1005, 1005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p33_1_2_0_4_3_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{},
                       Var<5>{}) %= edge(Var<1>{}, Var<2>{}) &&
                                    edge(Var<0>{}, Var<4>{}) &&
                                    edge(Var<3>{}, Var<5>{}));
    edge.insert(
        df::Relation<Edge>::from_vec({{1, 2}, {1000, 1004}, {2003, 2005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {
        {1, 1, 2, 1, 2, 2},
        {1, 1, 2, 1000, 2, 1004},
        {1, 1, 2, 2003, 2, 2005},
        {1, 1000, 1004, 1, 2, 2},
        {1, 1000, 1004, 1000, 2, 1004},
        {1, 1000, 1004, 2003, 2, 2005},
        {1, 2003, 2005, 1, 2, 2},
        {1, 2003, 2005, 1000, 2, 1004},
        {1, 2003, 2005, 2003, 2, 2005},
        {1000, 1, 2, 1, 1004, 2},
        {1000, 1, 2, 1000, 1004, 1004},
        {1000, 1, 2, 2003, 1004, 2005},
        {1000, 1000, 1004, 1, 1004, 2},
        {1000, 1000, 1004, 1000, 1004, 1004},
        {1000, 1000, 1004, 2003, 1004, 2005},
        {1000, 2003, 2005, 1, 1004, 2},
        {1000, 2003, 2005, 1000, 1004, 1004},
        {1000, 2003, 2005, 2003, 1004, 2005},
        {2003, 1, 2, 1, 2005, 2},
        {2003, 1, 2, 1000, 2005, 1004},
        {2003, 1, 2, 2003, 2005, 2005},
        {2003, 1000, 1004, 1, 2005, 2},
        {2003, 1000, 1004, 1000, 2005, 1004},
        {2003, 1000, 1004, 2003, 2005, 2005},
        {2003, 2003, 2005, 1, 2005, 2},
        {2003, 2003, 2005, 1000, 2005, 1004},
        {2003, 2003, 2005, 2003, 2005, 2005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p34_0_2_1_4_3_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{},
                       Var<5>{}) %= edge(Var<0>{}, Var<2>{}) &&
                                    edge(Var<1>{}, Var<4>{}) &&
                                    edge(Var<3>{}, Var<5>{}));
    edge.insert(
        df::Relation<Edge>::from_vec({{0, 2}, {1001, 1004}, {2003, 2005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {
        {0, 0, 2, 0, 2, 2},
        {0, 0, 2, 1001, 2, 1004},
        {0, 0, 2, 2003, 2, 2005},
        {0, 1001, 2, 0, 1004, 2},
        {0, 1001, 2, 1001, 1004, 1004},
        {0, 1001, 2, 2003, 1004, 2005},
        {0, 2003, 2, 0, 2005, 2},
        {0, 2003, 2, 1001, 2005, 1004},
        {0, 2003, 2, 2003, 2005, 2005},
        {1001, 0, 1004, 0, 2, 2},
        {1001, 0, 1004, 1001, 2, 1004},
        {1001, 0, 1004, 2003, 2, 2005},
        {1001, 1001, 1004, 0, 1004, 2},
        {1001, 1001, 1004, 1001, 1004, 1004},
        {1001, 1001, 1004, 2003, 1004, 2005},
        {1001, 2003, 1004, 0, 2005, 2},
        {1001, 2003, 1004, 1001, 2005, 1004},
        {1001, 2003, 1004, 2003, 2005, 2005},
        {2003, 0, 2005, 0, 2, 2},
        {2003, 0, 2005, 1001, 2, 1004},
        {2003, 0, 2005, 2003, 2, 2005},
        {2003, 1001, 2005, 0, 1004, 2},
        {2003, 1001, 2005, 1001, 1004, 1004},
        {2003, 1001, 2005, 2003, 1004, 2005},
        {2003, 2003, 2005, 0, 2005, 2},
        {2003, 2003, 2005, 1001, 2005, 1004},
        {2003, 2003, 2005, 2003, 2005, 2005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p35_2_3_1_4_0_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{},
                       Var<5>{}) %= edge(Var<2>{}, Var<3>{}) &&
                                    edge(Var<1>{}, Var<4>{}) &&
                                    edge(Var<0>{}, Var<5>{}));
    edge.insert(
        df::Relation<Edge>::from_vec({{2, 3}, {1001, 1004}, {2000, 2005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {
        {2, 2, 2, 3, 3, 3},
        {2, 2, 1001, 1004, 3, 3},
        {2, 2, 2000, 2005, 3, 3},
        {2, 1001, 2, 3, 1004, 3},
        {2, 1001, 1001, 1004, 1004, 3},
        {2, 1001, 2000, 2005, 1004, 3},
        {2, 2000, 2, 3, 2005, 3},
        {2, 2000, 1001, 1004, 2005, 3},
        {2, 2000, 2000, 2005, 2005, 3},
        {1001, 2, 2, 3, 3, 1004},
        {1001, 2, 1001, 1004, 3, 1004},
        {1001, 2, 2000, 2005, 3, 1004},
        {1001, 1001, 2, 3, 1004, 1004},
        {1001, 1001, 1001, 1004, 1004, 1004},
        {1001, 1001, 2000, 2005, 1004, 1004},
        {1001, 2000, 2, 3, 2005, 1004},
        {1001, 2000, 1001, 1004, 2005, 1004},
        {1001, 2000, 2000, 2005, 2005, 1004},
        {2000, 2, 2, 3, 3, 2005},
        {2000, 2, 1001, 1004, 3, 2005},
        {2000, 2, 2000, 2005, 3, 2005},
        {2000, 1001, 2, 3, 1004, 2005},
        {2000, 1001, 1001, 1004, 1004, 2005},
        {2000, 1001, 2000, 2005, 1004, 2005},
        {2000, 2000, 2, 3, 2005, 2005},
        {2000, 2000, 1001, 1004, 2005, 2005},
        {2000, 2000, 2000, 2005, 2005, 2005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p36_2_3_0_4_1_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{},
                       Var<5>{}) %= edge(Var<2>{}, Var<3>{}) &&
                                    edge(Var<0>{}, Var<4>{}) &&
                                    edge(Var<1>{}, Var<5>{}));
    edge.insert(
        df::Relation<Edge>::from_vec({{2, 3}, {1000, 1004}, {2001, 2005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {
        {2, 2, 2, 3, 3, 3},
        {2, 2, 1000, 1004, 3, 3},
        {2, 2, 2001, 2005, 3, 3},
        {2, 1000, 2, 3, 3, 1004},
        {2, 1000, 1000, 1004, 3, 1004},
        {2, 1000, 2001, 2005, 3, 1004},
        {2, 2001, 2, 3, 3, 2005},
        {2, 2001, 1000, 1004, 3, 2005},
        {2, 2001, 2001, 2005, 3, 2005},
        {1000, 2, 2, 3, 1004, 3},
        {1000, 2, 1000, 1004, 1004, 3},
        {1000, 2, 2001, 2005, 1004, 3},
        {1000, 1000, 2, 3, 1004, 1004},
        {1000, 1000, 1000, 1004, 1004, 1004},
        {1000, 1000, 2001, 2005, 1004, 1004},
        {1000, 2001, 2, 3, 1004, 2005},
        {1000, 2001, 1000, 1004, 1004, 2005},
        {1000, 2001, 2001, 2005, 1004, 2005},
        {2001, 2, 2, 3, 2005, 3},
        {2001, 2, 1000, 1004, 2005, 3},
        {2001, 2, 2001, 2005, 2005, 3},
        {2001, 1000, 2, 3, 2005, 1004},
        {2001, 1000, 1000, 1004, 2005, 1004},
        {2001, 1000, 2001, 2005, 2005, 1004},
        {2001, 2001, 2, 3, 2005, 2005},
        {2001, 2001, 1000, 1004, 2005, 2005},
        {2001, 2001, 2001, 2005, 2005, 2005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p37_1_3_2_4_0_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{},
                       Var<5>{}) %= edge(Var<1>{}, Var<3>{}) &&
                                    edge(Var<2>{}, Var<4>{}) &&
                                    edge(Var<0>{}, Var<5>{}));
    edge.insert(
        df::Relation<Edge>::from_vec({{1, 3}, {1002, 1004}, {2000, 2005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {
        {1, 1, 1, 3, 3, 3},
        {1, 1, 1002, 3, 1004, 3},
        {1, 1, 2000, 3, 2005, 3},
        {1, 1002, 1, 1004, 3, 3},
        {1, 1002, 1002, 1004, 1004, 3},
        {1, 1002, 2000, 1004, 2005, 3},
        {1, 2000, 1, 2005, 3, 3},
        {1, 2000, 1002, 2005, 1004, 3},
        {1, 2000, 2000, 2005, 2005, 3},
        {1002, 1, 1, 3, 3, 1004},
        {1002, 1, 1002, 3, 1004, 1004},
        {1002, 1, 2000, 3, 2005, 1004},
        {1002, 1002, 1, 1004, 3, 1004},
        {1002, 1002, 1002, 1004, 1004, 1004},
        {1002, 1002, 2000, 1004, 2005, 1004},
        {1002, 2000, 1, 2005, 3, 1004},
        {1002, 2000, 1002, 2005, 1004, 1004},
        {1002, 2000, 2000, 2005, 2005, 1004},
        {2000, 1, 1, 3, 3, 2005},
        {2000, 1, 1002, 3, 1004, 2005},
        {2000, 1, 2000, 3, 2005, 2005},
        {2000, 1002, 1, 1004, 3, 2005},
        {2000, 1002, 1002, 1004, 1004, 2005},
        {2000, 1002, 2000, 1004, 2005, 2005},
        {2000, 2000, 1, 2005, 3, 2005},
        {2000, 2000, 1002, 2005, 1004, 2005},
        {2000, 2000, 2000, 2005, 2005, 2005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p38_0_3_2_4_1_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{},
                       Var<5>{}) %= edge(Var<0>{}, Var<3>{}) &&
                                    edge(Var<2>{}, Var<4>{}) &&
                                    edge(Var<1>{}, Var<5>{}));
    edge.insert(
        df::Relation<Edge>::from_vec({{0, 3}, {1002, 1004}, {2001, 2005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {
        {0, 0, 0, 3, 3, 3},
        {0, 0, 1002, 3, 1004, 3},
        {0, 0, 2001, 3, 2005, 3},
        {0, 1002, 0, 3, 3, 1004},
        {0, 1002, 1002, 3, 1004, 1004},
        {0, 1002, 2001, 3, 2005, 1004},
        {0, 2001, 0, 3, 3, 2005},
        {0, 2001, 1002, 3, 1004, 2005},
        {0, 2001, 2001, 3, 2005, 2005},
        {1002, 0, 0, 1004, 3, 3},
        {1002, 0, 1002, 1004, 1004, 3},
        {1002, 0, 2001, 1004, 2005, 3},
        {1002, 1002, 0, 1004, 3, 1004},
        {1002, 1002, 1002, 1004, 1004, 1004},
        {1002, 1002, 2001, 1004, 2005, 1004},
        {1002, 2001, 0, 1004, 3, 2005},
        {1002, 2001, 1002, 1004, 1004, 2005},
        {1002, 2001, 2001, 1004, 2005, 2005},
        {2001, 0, 0, 2005, 3, 3},
        {2001, 0, 1002, 2005, 1004, 3},
        {2001, 0, 2001, 2005, 2005, 3},
        {2001, 1002, 0, 2005, 3, 1004},
        {2001, 1002, 1002, 2005, 1004, 1004},
        {2001, 1002, 2001, 2005, 2005, 1004},
        {2001, 2001, 0, 2005, 3, 2005},
        {2001, 2001, 1002, 2005, 1004, 2005},
        {2001, 2001, 2001, 2005, 2005, 2005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p39_1_3_0_4_2_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{},
                       Var<5>{}) %= edge(Var<1>{}, Var<3>{}) &&
                                    edge(Var<0>{}, Var<4>{}) &&
                                    edge(Var<2>{}, Var<5>{}));
    edge.insert(
        df::Relation<Edge>::from_vec({{1, 3}, {1000, 1004}, {2002, 2005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {
        {1, 1, 1, 3, 3, 3},
        {1, 1, 1000, 3, 3, 1004},
        {1, 1, 2002, 3, 3, 2005},
        {1, 1000, 1, 1004, 3, 3},
        {1, 1000, 1000, 1004, 3, 1004},
        {1, 1000, 2002, 1004, 3, 2005},
        {1, 2002, 1, 2005, 3, 3},
        {1, 2002, 1000, 2005, 3, 1004},
        {1, 2002, 2002, 2005, 3, 2005},
        {1000, 1, 1, 3, 1004, 3},
        {1000, 1, 1000, 3, 1004, 1004},
        {1000, 1, 2002, 3, 1004, 2005},
        {1000, 1000, 1, 1004, 1004, 3},
        {1000, 1000, 1000, 1004, 1004, 1004},
        {1000, 1000, 2002, 1004, 1004, 2005},
        {1000, 2002, 1, 2005, 1004, 3},
        {1000, 2002, 1000, 2005, 1004, 1004},
        {1000, 2002, 2002, 2005, 1004, 2005},
        {2002, 1, 1, 3, 2005, 3},
        {2002, 1, 1000, 3, 2005, 1004},
        {2002, 1, 2002, 3, 2005, 2005},
        {2002, 1000, 1, 1004, 2005, 3},
        {2002, 1000, 1000, 1004, 2005, 1004},
        {2002, 1000, 2002, 1004, 2005, 2005},
        {2002, 2002, 1, 2005, 2005, 3},
        {2002, 2002, 1000, 2005, 2005, 1004},
        {2002, 2002, 2002, 2005, 2005, 2005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}

TEST(AllPartitions, n6_p40_0_3_1_4_2_5) {
    Datalog dl;
    Predicate<int32_t, 6> result(dl);
    Predicate<int32_t, 2> edge(dl);
    dl.add_rule(result(Var<0>{}, Var<1>{}, Var<2>{}, Var<3>{}, Var<4>{},
                       Var<5>{}) %= edge(Var<0>{}, Var<3>{}) &&
                                    edge(Var<1>{}, Var<4>{}) &&
                                    edge(Var<2>{}, Var<5>{}));
    edge.insert(
        df::Relation<Edge>::from_vec({{0, 3}, {1001, 1004}, {2002, 2005}}));
    dl.solve();
    auto actual = result.extract();
    std::sort(actual.begin(), actual.end());
    std::vector<std::array<int32_t, 6>> expected = {
        {0, 0, 0, 3, 3, 3},
        {0, 0, 1001, 3, 3, 1004},
        {0, 0, 2002, 3, 3, 2005},
        {0, 1001, 0, 3, 1004, 3},
        {0, 1001, 1001, 3, 1004, 1004},
        {0, 1001, 2002, 3, 1004, 2005},
        {0, 2002, 0, 3, 2005, 3},
        {0, 2002, 1001, 3, 2005, 1004},
        {0, 2002, 2002, 3, 2005, 2005},
        {1001, 0, 0, 1004, 3, 3},
        {1001, 0, 1001, 1004, 3, 1004},
        {1001, 0, 2002, 1004, 3, 2005},
        {1001, 1001, 0, 1004, 1004, 3},
        {1001, 1001, 1001, 1004, 1004, 1004},
        {1001, 1001, 2002, 1004, 1004, 2005},
        {1001, 2002, 0, 1004, 2005, 3},
        {1001, 2002, 1001, 1004, 2005, 1004},
        {1001, 2002, 2002, 1004, 2005, 2005},
        {2002, 0, 0, 2005, 3, 3},
        {2002, 0, 1001, 2005, 3, 1004},
        {2002, 0, 2002, 2005, 3, 2005},
        {2002, 1001, 0, 2005, 1004, 3},
        {2002, 1001, 1001, 2005, 1004, 1004},
        {2002, 1001, 2002, 2005, 1004, 2005},
        {2002, 2002, 0, 2005, 2005, 3},
        {2002, 2002, 1001, 2005, 2005, 1004},
        {2002, 2002, 2002, 2005, 2005, 2005}};
    ASSERT_EQ(actual.size(), expected.size());
    for (size_t i = 0; i < actual.size(); i++)
        ASSERT_EQ(actual[i], expected[i]);
}
